[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Haron-Prime/Antares'

#tomlã€€syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'challenger-deep-theme/vim'

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'ajmwagar/vim-deus'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# nvim_colorscheme {{{
hook_add =
'''
    colorscheme hybrid
    set background=dark
'''
# }}}
